# Generated by Django 5.0.8 on 2025-05-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='Настройки'),
        ),
    ]
