# Generated by Django 5.0.8 on 2025-05-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=255, unique=True)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('NOT_ACTIVE', 'Неактивный')], default='NOT_ACTIVE', max_length=20)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='partners.partner')),
            ],
        ),
    ]
