# Generated by Django 5.0.8 on 2025-05-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_created_at_domain_public_id_domain_updated_at'),
        ('partners', '0004_alter_partner_options_alter_partner_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Домен', 'verbose_name_plural': 'Домены'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='code',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='partners.partner', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('NOT_ACTIVE', 'Неактивный')], default='NOT_ACTIVE', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.URLField(verbose_name='URL-адрес'),
        ),
    ]
