# Generated by Django 5.0.8 on 2025-05-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_alter_domain_options_alter_domain_code_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='domains',
        ),
    ]
