# Generated by Django 5.0.8 on 2025-05-17 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_alter_domain_partner'),
        ('partners', '0007_alter_partner_email_alter_partner_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='partners.partner', verbose_name='Партнёр'),
        ),
    ]
