# Generated by Django 5.0.8 on 2025-05-16 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(default='default', max_length=254),
        ),
        migrations.AddField(
            model_name='partner',
            name='inn',
            field=models.CharField(default='default', max_length=14),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='login',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logos/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='person_contact',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='public_id',
            field=models.CharField(default='default', editable=False, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
