# Generated by Django 5.0.8 on 2025-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_category_partner_created_at_partner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='partner',
            name='inn',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='partner',
            name='login',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='person_contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='public_id',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
