# Generated by Django 5.0.8 on 2025-05-16 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_category_alter_partner_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='inn',
            field=models.CharField(max_length=14, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='login',
            field=models.CharField(max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partner_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='person_contact',
            field=models.CharField(max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
