# Generated by Django 5.0.8 on 2025-05-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_partner_options_alter_partner_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partner',
            table='partners',
        ),
    ]
