# Generated by Django 5.0.8 on 2025-05-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_alter_domain_table'),
        ('partners', '0005_alter_partner_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partner_domain', to='domains.domain', verbose_name='Домен'),
            preserve_default=False,
        ),
    ]
