# Generated by Django 5.0.8 on 2025-05-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_partner_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
