# Generated by Django 5.0.8 on 2025-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_alter_partner_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='source',
            field=models.CharField(default='', max_length=255, verbose_name='Источник'),
            preserve_default=False,
        ),
    ]
