# Generated by Django 5.0.8 on 2025-04-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(default=dict)),
                ('source', models.CharField(max_length=255, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('applicant_first_name', models.CharField(max_length=255, verbose_name='Имя заявителя')),
                ('applicant_lastname', models.CharField(max_length=255, verbose_name='Фамилия заявителя')),
                ('applicant_middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество заявителя')),
                ('applicant_phone_number', models.CharField(max_length=255, verbose_name='Номер заявителя')),
                ('status', models.CharField(choices=[('open', 'Создано'), ('closed', 'Закрыта')], max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatioProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='proposal.proposal')),
            ],
            options={
                'db_table': 'creatio_proposals',
            },
        ),
    ]
