# Generated by Django 5.0.8 on 2025-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='applicant_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя заявителя'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='applicant_lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия заявителя'),
        ),
    ]
