# Generated by Django 5.0.8 on 2025-05-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_proposal_applicant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='applicant_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
    ]
